info:
  namespace: cleric
items:
  cleric_mace:
    display_name: "cleric_mace"
    permission: cleric_mace
    resource:
      material: STONE_SWORD
      model_id: 2045
      generate: false
      model_path: cleric_model/cleric_mace
  cleric_mace_shiny:
    display_name: "cleric_mace_shiny"
    permission: cleric_mace_shiny
    resource:
      material: STONE_SWORD
      model_id: 2046
      generate: false
      model_path: cleric_model/cleric_mace_shiny
  icon_dawnbringer_angel:
    display_name: "icon_dawnbringer_angel"
    permission: icon_dawnbringer_angel
    resource:
      material: COAL
      model_id: 2139
      generate: false
      model_path: cleric_model/icon_dawnbringer_angel
  icon_divine_immolation:
    display_name: "icon_divine_immolation"
    permission: icon_divine_immolation
    resource:
      material: COAL
      model_id: 2140
      generate: false
      model_path: cleric_model/icon_divine_immolation
  icon_luminous_wave:
    display_name: "icon_luminous_wave"
    permission: icon_luminous_wave
    resource:
      material: COAL
      model_id: 2141
      generate: false
      model_path: cleric_model/icon_luminous_wave
  icon_blessing_of_the_white_lantern:
    display_name: "icon_blessing_of_the_white_lantern"
    permission: icon_blessing_of_the_white_lantern
    resource:
      material: COAL
      model_id: 2142
      generate: false
      model_path: cleric_model/icon_blessing_of_the_white_lantern
  icon_divine_cross:
    display_name: "icon_divine_cross"
    permission: icon_divine_cross
    resource:
      material: COAL
      model_id: 2143
      generate: false
      model_path: cleric_model/icon_divine_cross
  icon_tears_of_god:
    display_name: "icon_tears_of_god"
    permission: icon_tears_of_god
    resource:
      material: COAL
      model_id: 2144
      generate: false
      model_path: cleric_model/icon_tears_of_god
  icon_divine_punishment:
    display_name: "icon_divine_punishment"
    permission: icon_divine_punishment
    resource:
      material: COAL
      model_id: 2145
      generate: false
      model_path: cleric_model/icon_divine_punishment
  divine_immolation_1:
    display_name: "divine_immolation_1"
    permission: divine_immolation_1
    resource:
      material: PAPER
      model_id: 2738
      generate: false
      model_path: cleric_model/divine_immolation_1
  divine_immolation_2:
    display_name: "divine_immolation_2"
    permission: divine_immolation_2
    resource:
      material: PAPER
      model_id: 2739
      generate: false
      model_path: cleric_model/divine_immolation_2
  divine_immolation_3:
    display_name: "divine_immolation_3"
    permission: divine_immolation_3
    resource:
      material: PAPER
      model_id: 2740
      generate: false
      model_path: cleric_model/divine_immolation_3
  divine_immolation_4:
    display_name: "divine_immolation_4"
    permission: divine_immolation_4
    resource:
      material: PAPER
      model_id: 2741
      generate: false
      model_path: cleric_model/divine_immolation_4
  divine_immolation_5:
    display_name: "divine_immolation_5"
    permission: divine_immolation_5
    resource:
      material: PAPER
      model_id: 2742
      generate: false
      model_path: cleric_model/divine_immolation_5
  divine_immolation_6:
    display_name: "divine_immolation_6"
    permission: divine_immolation_6
    resource:
      material: PAPER
      model_id: 2743
      generate: false
      model_path: cleric_model/divine_immolation_6
  divine_impact_1:
    display_name: "divine_impact_1"
    permission: divine_impact_1
    resource:
      material: PAPER
      model_id: 2744
      generate: false
      model_path: cleric_model/divine_impact_1
  divine_impact_2:
    display_name: "divine_impact_2"
    permission: divine_impact_2
    resource:
      material: PAPER
      model_id: 2745
      generate: false
      model_path: cleric_model/divine_impact_2
  divine_impact_3:
    display_name: "divine_impact_3"
    permission: divine_impact_3
    resource:
      material: PAPER
      model_id: 2746
      generate: false
      model_path: cleric_model/divine_impact_3
  divine_impact_4:
    display_name: "divine_impact_4"
    permission: divine_impact_4
    resource:
      material: PAPER
      model_id: 2747
      generate: false
      model_path: cleric_model/divine_impact_4
  divine_impact_5:
    display_name: "divine_impact_5"
    permission: divine_impact_5
    resource:
      material: PAPER
      model_id: 2748
      generate: false
      model_path: cleric_model/divine_impact_5
  divine_impact_6:
    display_name: "divine_impact_6"
    permission: divine_impact_6
    resource:
      material: PAPER
      model_id: 2749
      generate: false
      model_path: cleric_model/divine_impact_6
  divine_impact_7:
    display_name: "divine_impact_7"
    permission: divine_impact_7
    resource:
      material: PAPER
      model_id: 2750
      generate: false
      model_path: cleric_model/divine_impact_7
  divine_impact_8:
    display_name: "divine_impact_8"
    permission: divine_impact_8
    resource:
      material: PAPER
      model_id: 2751
      generate: false
      model_path: cleric_model/divine_impact_8
  luminous_wave_1:
    display_name: "luminous_wave_1"
    permission: luminous_wave_1
    resource:
      material: PAPER
      model_id: 2752
      generate: false
      model_path: cleric_model/luminous_wave_1
  luminous_wave_2:
    display_name: "luminous_wave_2"
    permission: luminous_wave_2
    resource:
      material: PAPER
      model_id: 2753
      generate: false
      model_path: cleric_model/luminous_wave_2
  luminous_wave_3:
    display_name: "luminous_wave_3"
    permission: luminous_wave_3
    resource:
      material: PAPER
      model_id: 2754
      generate: false
      model_path: cleric_model/luminous_wave_3
  luminous_wave_4:
    display_name: "luminous_wave_4"
    permission: luminous_wave_4
    resource:
      material: PAPER
      model_id: 2755
      generate: false
      model_path: cleric_model/luminous_wave_4
  luminous_wave_5:
    display_name: "luminous_wave_5"
    permission: luminous_wave_5
    resource:
      material: PAPER
      model_id: 2756
      generate: false
      model_path: cleric_model/luminous_wave_5
  luminous_wave_6:
    display_name: "luminous_wave_6"
    permission: luminous_wave_6
    resource:
      material: PAPER
      model_id: 2757
      generate: false
      model_path: cleric_model/luminous_wave_6
  luminous_wave_7:
    display_name: "luminous_wave_7"
    permission: luminous_wave_7
    resource:
      material: PAPER
      model_id: 2758
      generate: false
      model_path: cleric_model/luminous_wave_7
  luminous_wave_8:
    display_name: "luminous_wave_8"
    permission: luminous_wave_8
    resource:
      material: PAPER
      model_id: 2759
      generate: false
      model_path: cleric_model/luminous_wave_8
  luminous_wave_9:
    display_name: "luminous_wave_9"
    permission: luminous_wave_9
    resource:
      material: PAPER
      model_id: 2760
      generate: false
      model_path: cleric_model/luminous_wave_9
  tear_impact_1:
    display_name: "tear_impact_1"
    permission: tear_impact_1
    resource:
      material: PAPER
      model_id: 2761
      generate: false
      model_path: cleric_model/tear_impact_1
  tear_impact_2:
    display_name: "tear_impact_2"
    permission: tear_impact_2
    resource:
      material: PAPER
      model_id: 2762
      generate: false
      model_path: cleric_model/tear_impact_2
  tear_impact_3:
    display_name: "tear_impact_3"
    permission: tear_impact_3
    resource:
      material: PAPER
      model_id: 2763
      generate: false
      model_path: cleric_model/tear_impact_3
  tear_impact_4:
    display_name: "tear_impact_4"
    permission: tear_impact_4
    resource:
      material: PAPER
      model_id: 2764
      generate: false
      model_path: cleric_model/tear_impact_4
  tear_impact_5:
    display_name: "tear_impact_5"
    permission: tear_impact_5
    resource:
      material: PAPER
      model_id: 2765
      generate: false
      model_path: cleric_model/tear_impact_5
  tear_impact_6:
    display_name: "tear_impact_6"
    permission: tear_impact_6
    resource:
      material: PAPER
      model_id: 2766
      generate: false
      model_path: cleric_model/tear_impact_6
  tear_impact_7:
    display_name: "tear_impact_7"
    permission: tear_impact_7
    resource:
      material: PAPER
      model_id: 2767
      generate: false
      model_path: cleric_model/tear_impact_7
  tear_impact_8:
    display_name: "tear_impact_8"
    permission: tear_impact_8
    resource:
      material: PAPER
      model_id: 2768
      generate: false
      model_path: cleric_model/tear_impact_8
  